[project]
name = "yandex_smart_home"
version = "1.1.2.dev0"
requires-python = "~=3.14.2"

[dependency-groups]
test = [
    "pytest-homeassistant-custom-component==0.13.321",
    "mypy==1.19.1",
]
homeassistant = [
    "homeassistant==2026.4.0",
    "colorlog>=6.9.0",
]
homeassistant-components = [
    "hassil>=3.5.0",
    "home-assistant-intents>=2026.3.3",
    "pyturbojpeg>=1.8.2",

    # assist_pipeline dependencies
    "pymicro-vad==1.0.1",
    "pyspeex-noise==1.0.2",
    "mutagen>=1.47.0",
]
lint = [
    "ruff==0.15.8",
]
tox = [
    "tox>=4.23.2",
    "tox-uv>=1.26.0",
]
docs = [
    "mkdocs==1.6.1",
    "mkdocs-material==9.6.12",
    "mkdocs-material-extensions==1.3.1",
    "mkdocs-glightbox==0.4.0",
    "mike==2.1.3",
]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",       # pydocstyle
    "TD",      # flake8-todos
    "FBT",     # flake8-boolean-trap
    "FIX",     # flake8-fixme
    "ANN204",  # missing-return-type-special-method
    "ANN401",  # any-type
    "B904",    # raise-without-from-inside-except
    "C901",    # complex-structure
    "COM812",  # missing-trailing-comma
    "EM101",   # raw-string-in-exception
    "EM102",   # f-string-in-exception
    "G004",    # logging-f-string
    "PLC0105", # type-name-incorrect-variance
    "PLC0415", # import-outside-top-level
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "PLR2004", # magic-value-comparison
    "RUF012",  # mutable-class-default
    "RUF023",  # unsorted-dunder-slots
    "S101",    # assert
    "S105",    # hardcoded-password-string
    "SIM108",  # if-else-block-instead-of-if-exp
    "SLF001",  # private-member-access
    "TC001",   # typing-only-first-party-import
    "TC002",   # typing-only-third-party-import
    "TC003",   # typing-only-standard-library-import
    "TC006",   # runtime-cast-value
    "TRY003",  # raise-vanilla-args
    "TRY301",  # raise-within-try
    "TRY400",  # error-instead-of-exception
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["TRY002", "PT011", "S"]
"tests/test_schema.py" = ["F403", "F405"]
"tests/test_property.py" = ["ERA001"]
"custom_components/yandex_smart_home/schema/*.py" = ["F403"]

[tool.ruff.lint.isort]
force-sort-within-sections = true
combine-as-imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-p no:aiohttp"
verbosity_assertions = 2

[tool.coverage.report]
exclude_also = [
    "raise NotImplementedError",
]
omit = ["tests/*"]

[tool.pyright]
reportPrivateImportUsage = "none"
reportIncompatibleVariableOverride = "none"

[tool.mypy]
python_version = "3.14"
plugins = ["pydantic.mypy"]
follow_untyped_imports = true
local_partial_types = true
strict_equality = true
strict_bytes = true
no_implicit_optional = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
enable_error_code = [
    "ignore-without-code",
    "redundant-self",
    "truthy-iterable",
]
extra_checks = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
warn_return_any = true
warn_unreachable = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_calls = false
disable_error_code = [
    "func-returns-value",
]

[[tool.mypy.overrides]]
module = "tests.test_repairs"
disallow_any_generics = false

[tool.tox]
env_list = [
    "type",
    "2025_12",
    "2026_1",
    "2026_2",
    "2026_3",
    "2026_4",
]

[tool.tox.env_run_base]
description = "Run test under {env_python}"
base_python = ["py314"]
runner = "uv-venv-lock-runner"
commands = [
    ["pytest", "--cov", "--cov-report=xml:{env_dir}/coverage.xml", "-n=auto"],
]

[tool.tox.env_run_base.setenv]
PYTHONDONTWRITEBYTECODE = "1"
MYPY_CACHE_DIR = "{env_dir}/.cache/mypy"

[tool.tox.env.2025_12]
base_python = ["py313"]
uv_sync_flags = ["--directory=tests/env/2025_12"]

[tool.tox.env.2026_1]
base_python = ["py313"]
uv_sync_flags = ["--directory=tests/env/2026_1"]

[tool.tox.env.2026_2]
base_python = ["py313"]
uv_sync_flags = ["--directory=tests/env/2026_2"]

[tool.tox.env.2026_3]
uv_sync_flags = ["--directory=tests/env/2026_3"]

[tool.tox.env.2026_4]
uv_sync_flags = ["--directory=tests/env/2026_4"]

[tool.tox.env.type]
description = "Run type checks under {env_python}"
dependency_groups = ["test"]
commands = [
    ["mypy", "."],
]
