[project]
name = "yandex_smart_home_test_env"
version = "2024.12"
requires-python = "~=3.13.0"
dependencies = [
    "pytest-homeassistant-custom-component==0.13.195",
    "home-assistant-intents==2024.11.27",
    "hassil==2.0.4",
    "mutagen==1.47.0",
    "ha-ffmpeg==3.2.2",
    "pymicro-vad==1.0.2",
    "pyspeex_noise==1.0.2",
]
