name: Deploy docs

on:
  push:
    branches:
      - v*
      - dev

permissions:
  contents: write

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --only-group docs

      - name: Prepare environment
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo "SOURCE_DATE_EPOCH=$(git log -1 --format=%ct docs mkdocs.yml)" >> "${GITHUB_ENV}"

      - name: Deploy docs
        run: |
          VERSION="${GITHUB_REF_NAME}"
          [ "${GITHUB_REF_NAME}" == "dev" ] && VERSION="v1.1.x"
          uv run mike deploy --push --branch gh-pages "${VERSION}"
