name: linting

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      - name: install deps
        run: pip install -r requirements_lint.txt

      - name: flake8 lint
        uses: TrueBrain/actions-flake8@v2
        with:
          path: custom_components

      - name: flake8 lint tests
        uses: TrueBrain/actions-flake8@v2
        with:
          path: tests
